"""added TipRead model

Revision ID: 048ff34e1751
Revises: f874b97ccdad
Create Date: 2023-03-30 10:11:21.599959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048ff34e1751'
down_revision = 'f874b97ccdad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'daily_tips', ['header'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_tips', type_='unique')
    # ### end Alembic commands ###
