"""made telegram_user_id in User not unique

Revision ID: 0df4cde7c80f
Revises: 327df5e49e0c
Create Date: 2023-03-28 20:11:41.379645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0df4cde7c80f'
down_revision = '327df5e49e0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
