"""edited Bookmark model

Revision ID: 1bc845556c40
Revises: 1c93c3afcdb7
Create Date: 2023-03-17 10:05:34.265652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc845556c40'
down_revision = '1c93c3afcdb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
