"""added 2 fields to ParentingTip

Revision ID: 1c93c3afcdb7
Revises: ca2de8c03ff9
Create Date: 2023-03-16 12:03:52.298252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c93c3afcdb7'
down_revision = 'ca2de8c03ff9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parenting_tips', sa.Column('useful_from_day', sa.Integer(), nullable=True))
    op.add_column('parenting_tips', sa.Column('useful_until_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parenting_tips', 'useful_until_day')
    op.drop_column('parenting_tips', 'useful_from_day')
    # ### end Alembic commands ###
