"""add referral ID to users

Revision ID: 219c2fcd14f5
Revises: 2ae7b96a302f
Create Date: 2023-03-09 13:10:48.541893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219c2fcd14f5'
down_revision = '2ae7b96a302f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
