"""Deleted redundant Tag model, added AdLog model 

Revision ID: 29e9615309bc
Revises: dec911c29cf9
Create Date: 2023-04-10 19:08:24.167592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e9615309bc'
down_revision = 'dec911c29cf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_id', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_table('tags_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags_association',
    sa.Column('tip_id', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['tip_id'], ['parenting_tips.id'], )
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('start_age', sa.INTEGER(), nullable=True),
    sa.Column('end_age', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    # ### end Alembic commands ###
