"""added bookmarks table

Revision ID: 2a73a3365152
Revises: 5573cb771052
Create Date: 2023-03-11 14:54:02.102631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a73a3365152'
down_revision = '5573cb771052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
