"""add referral ID to users

Revision ID: 2ae7b96a302f
Revises: 99cf4e8d3edf
Create Date: 2023-03-09 13:07:43.901514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae7b96a302f'
down_revision = '99cf4e8d3edf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_id')
    # ### end Alembic commands ###
