"""added blocked_bot to User

Revision ID: 329622be0d8b
Revises: 982cec8853d9
Create Date: 2023-03-14 12:24:58.609885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329622be0d8b'
down_revision = '982cec8853d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blocked_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked_bot')
    # ### end Alembic commands ###
