"""added passed_basic_reg to User model

Revision ID: 35bb9db0a103
Revises: cabd40861142
Create Date: 2023-03-17 13:22:27.817261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35bb9db0a103'
down_revision = 'cabd40861142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passed_basic_reg', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passed_basic_reg')
    # ### end Alembic commands ###
