"""updated ParentingTip model

Revision ID: 4120453e8fd7
Revises: 219c2fcd14f5
Create Date: 2023-03-09 13:41:39.067301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4120453e8fd7'
down_revision = '219c2fcd14f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parenting_tips', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parenting_tips', 'created_at')
    # ### end Alembic commands ###
