"""Updated ParentingTip, added Advertisement model and updated AdLog

Revision ID: 4691b8df1635
Revises: 7ded2759106f
Create Date: 2023-04-10 21:09:20.569640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4691b8df1635'
down_revision = '7ded2759106f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisement_logs', sa.Column('ad_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'advertisement_logs', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement_logs', 'advertisements', ['ad_id'], ['id'])
    op.drop_column('advertisement_logs', 'tip_id')
    op.drop_column('parenting_tips', 'advertisement')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parenting_tips', sa.Column('advertisement', sa.VARCHAR(), nullable=True))
    op.add_column('advertisement_logs', sa.Column('tip_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'advertisement_logs', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement_logs', 'parenting_tips', ['tip_id'], ['id'])
    op.drop_column('advertisement_logs', 'ad_id')
    # ### end Alembic commands ###
