"""added bookmarks table

Revision ID: 5573cb771052
Revises: 5ebaffe6b3e4
Create Date: 2023-03-10 22:52:38.825293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5573cb771052'
down_revision = '5ebaffe6b3e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
