"""updatre child model

Revision ID: 5ebaffe6b3e4
Revises: 4120453e8fd7
Create Date: 2023-03-10 12:25:09.697775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebaffe6b3e4'
down_revision = '4120453e8fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('sex', sa.String(), nullable=True))
    op.drop_column('children', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.drop_column('children', 'sex')
    # ### end Alembic commands ###
