"""Updated AdLog model

Revision ID: 7ded2759106f
Revises: 29e9615309bc
Create Date: 2023-04-10 20:57:28.406988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ded2759106f'
down_revision = '29e9615309bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
