"""added bookmarks table

Revision ID: 982cec8853d9
Revises: 2a73a3365152
Create Date: 2023-03-14 12:23:42.579016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982cec8853d9'
down_revision = '2a73a3365152'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
