"""updated User model with is_banned and last_seen

Revision ID: bb3482c98204
Revises: 35bb9db0a103
Create Date: 2023-03-23 13:10:20.214270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3482c98204'
down_revision = '35bb9db0a103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
