"""Updated AdvertisementLog model

Revision ID: c92b5df03331
Revises: d5b22994181b
Create Date: 2023-04-11 10:18:15.546398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92b5df03331'
down_revision = 'd5b22994181b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advertisement_logs', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'advertisement_logs', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement_logs', 'advertisements', ['ad_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'advertisement_logs', type_='foreignkey')
    op.create_foreign_key(None, 'advertisement_logs', 'advertisements', ['ad_id'], ['id'])
    op.alter_column('advertisement_logs', 'ad_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
