"""added additional fields to ParentingTip

Revision ID: ca2de8c03ff9
Revises: f644ecfbe567
Create Date: 2023-03-16 11:54:14.911597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2de8c03ff9'
down_revision = 'f644ecfbe567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parenting_tips', sa.Column('useful_from_day', sa.Integer(), nullable=False))
    op.add_column('parenting_tips', sa.Column('useful_until_day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parenting_tips', 'useful_until_day')
    op.drop_column('parenting_tips', 'useful_from_day')
    # ### end Alembic commands ###
