"""added passed_basic_reg to User model

Revision ID: cabd40861142
Revises: 1bc845556c40
Create Date: 2023-03-17 10:26:37.987441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabd40861142'
down_revision = '1bc845556c40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passed_basic_reg', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passed_basic_reg')
    # ### end Alembic commands ###
