"""Updated ParentingTip with advertisement column

Revision ID: dec911c29cf9
Revises: 0e3f6ad24a47
Create Date: 2023-04-07 23:26:02.828969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec911c29cf9'
down_revision = '0e3f6ad24a47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parenting_tips', sa.Column('advertisement', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parenting_tips', 'advertisement')
    # ### end Alembic commands ###
