"""added additional fields to Tag model

Revision ID: f644ecfbe567
Revises: 329622be0d8b
Create Date: 2023-03-15 11:26:09.432736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f644ecfbe567'
down_revision = '329622be0d8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('start_age', sa.Integer(), nullable=True))
    op.add_column('tags', sa.Column('end_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'end_age')
    op.drop_column('tags', 'start_age')
    # ### end Alembic commands ###
