"""fixed a bug in DailyTip model

Revision ID: f874b97ccdad
Revises: 0df4cde7c80f
Create Date: 2023-03-28 21:59:17.701524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f874b97ccdad'
down_revision = '0df4cde7c80f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_tips', sa.Column('media', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'daily_tips', ['header'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_tips', type_='unique')
    op.drop_column('daily_tips', 'media')
    # ### end Alembic commands ###
